#======================================================================
# Project settings
#======================================================================
branches:
  only:
    - release/crtm_jedi

language: cpp

services:
  - docker

before_install:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_BRANCH
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - pwd
  - ls ${TRAVIS_BUILD_DIR}

  - docker pull jcsda/docker-clang-mpich-dev
  - docker images

script:
  - docker run -d -t --name clang_container -v ${TRAVIS_BUILD_DIR}:/jcsda/src_repo jcsda/docker-clang-mpich-dev
  - docker exec clang_container bash -c 'ls /jcsda/src_repo'
  - docker exec clang_container bash -c 'mkdir /build_container'
  - docker exec clang_container bash -c 'cd /build_container && ecbuild /jcsda/src_repo'
  - docker exec clang_container bash -c 'cd /build_container && make -j4'
  - docker exec clang_container bash -c 'cd /build_container && ctest --output-on-failure'
